name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/container/latest

      # - uses: ItsKarma/aws-cli@v1.70.0
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/container/latest
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}